# Generated by Django 3.2.6 on 2021-11-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crayonApp', '0003_auto_20211020_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_uuid', models.CharField(max_length=200)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
