# Generated by Django 3.2.6 on 2021-11-09 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crayonApp', '0005_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='upload_method',
        ),
    ]
