# Generated by Django 3.2.6 on 2021-11-11 20:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crayonApp', '0006_remove_file_upload_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_uuid',
        ),
        migrations.AddField(
            model_name='file',
            name='user_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crayonApp.user'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
