# Generated by Django 3.2.6 on 2021-11-11 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crayonApp', '0007_auto_20211111_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='room_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crayonApp.room'),
        ),
    ]
