# Generated by Django 3.2.6 on 2021-11-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crayonApp', '0008_file_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='ea04e532', editable=False, max_length=256, primary_key=True, serialize=False, unique=True),
        ),
    ]
