# Generated by Django 3.2.6 on 2021-11-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crayonApp', '0013_auto_20211121_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_attr',
            name='file_id',
        ),
        migrations.RemoveField(
            model_name='file_attr',
            name='room_id',
        ),
        migrations.RemoveField(
            model_name='file_attr',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='aa9cf57d', editable=False, max_length=256, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='File_attr',
        ),
    ]
