# Generated by Django 3.2.6 on 2021-11-21 12:03

import crayonApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crayonApp', '0014_auto_20211121_0502'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=crayonApp.models.user_directory_path)),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='fc982c2e', editable=False, max_length=256, primary_key=True, serialize=False, unique=True),
        ),
    ]
