# Generated by Django 3.2.6 on 2021-11-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crayonApp', '0017_auto_20211123_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='choice_text',
            field=models.CharField(max_length=256),
        ),
    ]
