# Generated by Django 3.2.6 on 2021-11-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crayonApp', '0018_alter_quiz_choice_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='context',
            field=models.CharField(default=0, max_length=256),
        ),
    ]
