# Generated by Django 3.2.6 on 2021-11-30 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crayonApp', '0019_choice_context'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='choice_text',
            new_name='quiz_context',
        ),
    ]
