# Generated by Django 3.2.6 on 2021-12-06 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crayonApp', '0021_rename_socre_choice_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_creater',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crayonApp.user'),
        ),
    ]
